In [3]:
import numpy as np

In [5]:
# Q1

In [7]:
arr = np.array([1, 2, 3, 6, 4, 5])

In [9]:
reverse = arr[::-1]

In [11]:
reverse

array([5, 4, 6, 3, 2, 1])

In [13]:
# Q1 b

In [15]:
array1 = np.array([[1, 2, 3],
                   [2, 4, 5],
                   [1, 2, 3]])

In [21]:
flat1 = array1.flatten()
print(flat1)

[1 2 3 2 4 5 1 2 3]


In [25]:
flat2 = array1.ravel()
print(flat2)

[1 2 3 2 4 5 1 2 3]


In [27]:
# Q1 c

In [29]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

print("ElementWise", arr1 == arr2)

ElementWise [[ True  True]
 [ True  True]]


In [31]:
# Q1e

In [33]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

total_sum = gfg.sum()
row_sum = gfg.sum(axis=1)
col_sum = gfg.sum(axis=0)

print("Sum of all elements:", total_sum)
print("Row-wise sum:\n", row_sum)
print("Column-wise sum:\n", col_sum)

Sum of all elements: 45
Row-wise sum:
 [[14]
 [16]
 [15]]
Column-wise sum:
 [[20  9 16]]


In [35]:
n_array = np.array([[55, 25, 15],
                    [30, 44,  2],
                    [11, 45, 77]])

diag_sum = np.trace(n_array)
eigvals, eigvecs = np.linalg.eig(n_array)
inverse = np.linalg.inv(n_array)
determinant = np.linalg.det(n_array)

print("Sum of diagonal elements:", diag_sum)
print("\nEigenvalues:\n", eigvals)
print("\nEigenvectors (columns correspond to eigenvalues):\n", eigvecs)
print("\nInverse of matrix:\n", inverse)
print("\nDeterminant of matrix:", determinant)

Sum of diagonal elements: 176

Eigenvalues:
 [98.16835147 28.097044   49.73460452]

Eigenvectors (columns correspond to eigenvalues):
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]

Inverse of matrix:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]

Determinant of matrix: 137180.0000000001


In [37]:
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])
product1 = np.dot(p1, q1)
cov1 = np.cov(p1, q1)
print(product1)
print(cov1)

[[16 19]
 [26 31]]
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


In [39]:
p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])
product2 = np.dot(p2, q2)
cov2 = np.cov(p2, q2)
print(product2)
print(cov2)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [41]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

inner_product = np.inner(x, y)
outer_product = np.outer(x, y)
cartesian_product = np.array(np.meshgrid(x.flatten(), y.flatten())).T.reshape(-1, 2)

print(inner_product)
print(outer_product)
print(cartesian_product)

[[17 52]
 [13 62]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
[[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [43]:
# Q2

In [45]:
array = np.array([[1, -2, 3], [-4, 5, -6]])

abs_array = np.abs(array)

percentile_flat = np.percentile(array, [25, 50, 75])
percentile_col = np.percentile(array, [25, 50, 75], axis=0)
percentile_row = np.percentile(array, [25, 50, 75], axis=1)

mean_flat = np.mean(array)
median_flat = np.median(array)
std_flat = np.std(array)

mean_col = np.mean(array, axis=0)
median_col = np.median(array, axis=0)
std_col = np.std(array, axis=0)

mean_row = np.mean(array, axis=1)
median_row = np.median(array, axis=1)
std_row = np.std(array, axis=1)

print(abs_array)
print(percentile_flat)
print(percentile_col)
print(percentile_row)
print(mean_flat, median_flat, std_flat)
print(mean_col, median_col, std_col)
print(mean_row, median_row, std_row)

[[1 2 3]
 [4 5 6]]
[-3.5 -0.5  2.5]
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
[[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
-0.5 -0.5 3.8622100754188224
[-1.5  1.5 -1.5] [-1.5  1.5 -1.5] [2.5 3.5 4.5]
[ 0.66666667 -1.66666667] [ 1. -4.] [2.05480467 4.78423336]


In [47]:
# Q2 B

In [49]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

floor_vals = np.floor(a)
ceil_vals = np.ceil(a)
trunc_vals = np.trunc(a)
round_vals = np.round(a)

In [51]:
floor_vals

array([-2., -2., -1.,  0.,  1.,  1.,  3.])

In [53]:
ceil_vals

array([-1., -1., -0.,  1.,  2.,  2.,  3.])

In [55]:
trunc_vals

array([-1., -1., -0.,  0.,  1.,  1.,  3.])

In [57]:
round_vals

array([-2., -2., -0.,  0.,  2.,  2.,  3.])

In [61]:
#Q3 a

In [63]:
array = np.array([10, 52, 62, 16, 16, 54, 453])

In [65]:
sorted_array = np.sort(array)
sorted_indices = np.argsort(array)
smallest_4 = np.sort(array)[:4]
largest_5 = np.sort(array)[-5:]

In [67]:
sorted_array

array([ 10,  16,  16,  52,  54,  62, 453])

In [69]:
sorted_indices

array([0, 3, 4, 1, 5, 2, 6], dtype=int64)

In [71]:
smallest_4

array([10, 16, 16, 52])

In [73]:
largest_5

array([ 16,  52,  54,  62, 453])

In [75]:
# Q3 b

In [77]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

In [79]:
int_elements = array[np.floor(array) == array]
float_elements = array[np.floor(array) != array]

In [81]:
int_elements

array([1., 2., 3., 2.])

In [83]:
float_elements

array([1.2, 2.2])